POST http://localhost:3003/api/blog
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJpY2hpZVAiLCJpZCI6IjVlY2U3NTZlZDFiYWZmMmFhZWE2ZjIwYiIsImlhdCI6MTU5MDY1Njk0Nn0.42VPTDYV1XNvyyqQhzv2nUXY6L9IAYZ8xH3GIyhcv_w

{
    "title": "Sample 9", "author": "Mark", "url":"https://mangolatte.dev", "likes": 100, "userId": "5ece756ed1baff2aaea6f20b"
}
