POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJpY2hpZVAiLCJpZCI6IjVlY2U3NTZlZDFiYWZmMmFhZWE2ZjIwYiIsImlhdCI6MTU5MDc0MDk0OH0.8AoVAbnRUPbRKF_1fOO_AULmnuJem3AzrdhIZaVi7nI

{
    "title": "Sample 2", "author": "James", "url":"https://mangolatte.dev", "likes": 10
}
